### ISSUE TITLE
VM Request

### ISSUE THREAD

**Issue by Ji0ngHan** [wrmelicher/ChromiumTaintTracking#4]
Hello William, 

I am trying to do some research for my team with the potential solution for detecting DOM XSS, and your paper looks interesting and promising. I tried to put things together as documented by the readme. However, things not going smoothly. I wonder if VM with code checked out is still available and I can use that. Let me know if any concerns. Thank you very much!

Best,
Jiong

**Comment by wrmelicher** [comment]
Hi!

If you send me an email to [my github username] at gmail dot com, I'll get
you set up with it.

Thanks,
Billy
